# create configmap for cwagent config
apiVersion: v1
data:
  # Configuration is in Json format. No matter what configure change you make,
  # please keep the Json blob valid.
  cwagentconfig.json: |
    {
      "namespace": "Production-Cluster",
      "metrics": {
        "metrics_collected": {
          "disk": {
            "measurement": [
             "used_percent"
            ],
            "metrics_collection_interval": 3600,
            "resources": [
              "/"
            ]
          }
        }
      }
    }

kind: ConfigMap
metadata:
  name: cwagentconfig
  namespace: amazon-cloudwatch

